#!/bin/sh
#
# acl-repos - Adds ACLs to /repos so www-data can read everything.
# unacl-repos - Removes _all_ ACLs from the /repos directory.
#
# This file is part of setup-cgit, an unofficial cgit how-to and scripts.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <https://creativecommons.org/publicdomain/zero/1.0/>.

set -f

msg() {
    printf '%s: %s: %s\n' "$0" "$1" "$2" >&2
}

warn() {
    msg 'warning' "$1"
}

die() {
    msg 'error' "$1"
    exit 1
}

if ! euid="$(id -u)"; then
    # If id failed, its empty output would compare equal to zero.
    warn "id failed with exit code $?, not sure if you're the superuser"
elif [ "$euid" -ne 0 ]; then
    warn 'you are not the superuser, this will probably fail'
fi

case "$(basename "$0")" in
acl-repos)
    setfacl -Rdm u:www-data:rx /repos
    setfacl -Rm u:www-data:rx /repos
    ;;
unacl-repos)
    setfacl -Rbn /repos
    ;;
*)
    die 'this utility must be named "acl-repos" or "unacl-repos"'
    ;;
esac
