#!/bin/sh
#
# deploy-cgitrc - install cgitrc in /etc
#
# This file is part of setup-cgit, an unofficial cgit how-to and scripts.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <https://creativecommons.org/publicdomain/zero/1.0/>.

rc='cgitrc'

if cmp -s "/etc/$rc" "$rc"; then
    printf '%s: note: %s is unchanged, not copying\n' "$0" "$rc" >&2
    exit 0
fi

install -bS.old -m 644 "$rc" /etc/
