#!/bin/sh
#
# deploy-redirect - modifies Apache2 configuration to send / to /cgit
#
# This file is part of setup-cgit, an unofficial cgit how-to and scripts.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

set -e
install -m 644 redirect.conf /etc/apache2/conf-available/
a2enconf -q redirect
systemctl reload apache2
