#!/bin/sh
#
# deploy-about-cgit - installs about-cgit.md to /var/www/html for a root readme
#
# This file is part of setup-cgit, an unofficial cgit how-to and scripts.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

install -m  644 about-cgit.md /var/www/html/
