#!/bin/sh
#
# install-services - installs APT packages for cgit and supporting software
#
# This file is part of setup-cgit, an unofficial cgit how-to and scripts.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

set -e

apt update

# Install all the packages that are likely to need to be installed, plus
# highlight so that it can be used as an alternative to pygments.
apt install apache2 cgit git highlight python3-docutils python3-markdown \
        python3-pygments

a2enconf -q cgit # Installing cgit may have done this already, but that's okay.
a2enmod -q cgid
systemctl restart apache2
