#!/bin/sh
#
# setup-all - attempt automatic installation and configuration of cgit
#
# This file is part of setup-cgit, an unofficial cgit how-to and scripts.
#
# Written in 2019 by Eliah Kagan <degeneracypressure@gmail.com>.
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain
# worldwide. This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along
# with this software. If not, see
# <http://creativecommons.org/publicdomain/zero/1.0/>.

set -f

msg() {
    printf '%s: %s: %s\n' "$0" "$1" "$2" >&2
}

warn() {
    msg 'warning' "$1"
}

die() {
    msg 'error' "$1"
    exit 1
}

if [ "$#" -eq 0 ]; then
    {
        curdir="$(realpath .)" &&
        scriptdir="$(realpath "$(dirname "$0")")" &&
        [ "$curdir" = "$scriptdir" ]
    } || die 'script not in CWD (use -f to force)'

    {
        euid="$(id -u)" && [ "$euid" -eq 0 ]
    } || die 'script not run as root (use -f to force)'
elif [ "$#" -ne 1 ]; then
    die 'too many arguments'
elif [ "$1" = '-f' ]; then
    warn 'not comparing CWD to script location'
else
    die "spurious argument \"$1\""
fi

set -e

./install-services
./deploy-cgitrc
./deploy-about-cgit
./deploy-acl-repos
acl-repos
./deploy-redirect

printf 'It all seems to have worked. Try visiting http://localhost/cgit.\n'
